@startuml deployment

node "raspberry server" as raspi_server{
    cloud "MQTT broker" as MQTT
    component CIPHER{
        cloud "Socket IO server" as SocketIO
        database "server storage" as server{
            artifact relays
            artifact servomotors
            artifact sequences
        }
    }
    node "client raspberry 3" as raspi_client_3{
        component "CIPHER client" as CIPHER_client_3
        CIPHER_client_3 -- MQTT
    }
    node "CIPHER-speech" as speech
    speech -- MQTT : "MQTT"
    CIPHER -- MQTT : "MQTT"

}
node "client raspberry 1" as raspi_client_1{
    component "CIPHER client" as CIPHER_client_1
    CIPHER_client_1 -- MQTT : "MQTT"
}
node "client raspberry 2" as raspi_client_2{
    component "CIPHER client" as CIPHER_client_2
    CIPHER_client_2 -- MQTT : "MQTT"
}

node "user client" as user {
    component webclient
    SocketIO -- webclient : "socket io"
}

@enduml
